// PWEBII/atividades/praticas-frameworks/two-frameworks-atv/app-angular-01/src/app/components/post/post.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-post',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './post.component.html',
  styleUrl: './post.component.css'
})
export class PostComponent {
  @Input() title: string = '';
  @Input() description: string = '';
  @Input() link: string = '';
}
<div style="margin-bottom: 20px;">
    <a [href]="link" target="_blank" style="text-decoration: none;">
      <h3 style="color: #5b7bb2; cursor: pointer;">{{ title }}</h3>
    </a>
    
    <p style="font-size: 12px; color: #666; font-style: italic;">
      {{ description }}
    </p>
  </div>

// PWEBII/atividades/praticas-frameworks/two-frameworks-atv/app-react-02/src/components/Post.jsx
function Post({ title, description, link }) {
    return (
      <div style={{ marginBottom: '20px' }}>
        
        <a 
          href={link} 
          target="_blank" 
          rel="https://alexmngn.medium.com/level-up-your-career-as-a-developer-2ec42c208b82"
          style={{ textDecoration: 'none' }} 
        >
          <h3 style={{ color: '#5b7bb2', cursor: 'pointer' }}>
            {title}
          </h3>
        </a>
  
        <p style={{ fontSize: '12px', color: '#666', fontStyle: 'italic' }}>
          {description}
        </p>
      </div>
    );
  }
  
  export default Post;
